pipeline {
  agent any

  environment {
    PROJECT_NAME = """${sh(
      returnStdout: true,
      script: 'echo "${JOB_NAME}" | awk -F"-" "{print \\$1}"'
    )}"""
    ENV_NAME = """${sh(
      returnStdout: true,
      script: 'echo "${JOB_NAME}" | awk -F"-" "{print \\$NF}"'
    )}"""
    INFO_COLOR = "#00BFFF"
  }

  stages {
    stage('Initialize') {
      steps {
        script {
          if (env.BRANCH_NAME == 'main' || env.BRANCH_NAME == 'staging') {
            sh 'ls ./config/${env.BRANCH_NAME}/'
          } else {
            sh 'ls ./config/sandbox/'
          }
        }
      }
    }

    stage('Plan') {
      steps {
        echo 'Planning World'
      }
    }

    stage('Approve') {
      when {
        branch 'main'
      }

      steps {
        timeout(unit: 'MINUTES', time: 1) {
          slackSend channel: "#jenkins", color: "${INFO_COLOR}", message: "[${env.PROJECT_NAME}]\n${JOB_NAME}を続行しても良いでしょうか？\n<$JOB_URL|ここをクリックしてJenkins上で承認 or 否認してください>"
          input id: "approver", message: "問題ない場合はProccedボタンを押してください"
        }
      }
    }

    stage('Apply') {
      steps {
        slackSend color: "${env.INFO_COLOR}", message: "Applyしたよー"
      }
    }
  }

  post {
    success {
      slackSend channel: "#jenkins", color: "good", message: "[${env.PROJECT_NAME}]\n<$BUILD_URL|${JOB_NAME}/$BUILD_NUMBER> sucessefully finished"
    }

    failure {
      slackSend channel: "#jenkins", attachments: [[title: "[${PROJECT_NAME}]", text: "<$BUILD_URL|${JOB_NAME}/$BUILD_NUMBER> failed", color: 'danger']]
    }

    aborted {
      slackSend channel: "#jenkins", color: "warning", message: "[${JOB_NAME}]\n<$BUILD_URL|$BUILD_NUMBER> has beeen aborted"
    }
  }
}
